ALTER TABLE click_event
    ADD COLUMN IF NOT EXISTS user_ip VARCHAR(50),
    ADD COLUMN IF NOT EXISTS user_country VARCHAR(100),
    ADD COLUMN IF NOT EXISTS user_region VARCHAR(100),
    ADD COLUMN IF NOT EXISTS user_city VARCHAR(100);

